version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: oil_attendance
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - oil-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: oil_attendance
    networks:
      - oil-network

  frontend:
    build:
      context: ./attendance-dashboard
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - oil-network

volumes:
  mysql-data:

networks:
  oil-network: